//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MannLabels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AltLabelItem
    {
        public int idx { get; set; }
        public string ItemNum { get; set; }
        public string AlterLabel { get; set; }
        public string CustProdId { get; set; }
        public bool ShowJulianNoSellby { get; set; }
    }
}
