//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MannLabels
{
    using System;
    using System.Collections.Generic;
    
    public partial class F0005
    {
        public string DRSY { get; set; }
        public string DRRT { get; set; }
        public string DRKY { get; set; }
        public string DRDL01 { get; set; }
        public string DRDL02 { get; set; }
        public string DRSPHD { get; set; }
        public string DRUDCO { get; set; }
        public string DRHRDC { get; set; }
        public string DRUSER { get; set; }
        public string DRPID { get; set; }
        public Nullable<decimal> DRUPMJ { get; set; }
        public string DRJOBN { get; set; }
        public Nullable<double> DRUPMT { get; set; }
    }
}
