//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MannLabels
{
    using System;
    using System.Collections.Generic;
    
    public partial class F4101
    {
        public double IMITM { get; set; }
        public string IMLITM { get; set; }
        public string IMAITM { get; set; }
        public string IMDSC1 { get; set; }
        public string IMDSC2 { get; set; }
        public string IMSRTX { get; set; }
        public string IMALN { get; set; }
        public string IMSRP1 { get; set; }
        public string IMSRP2 { get; set; }
        public string IMSRP3 { get; set; }
        public string IMSRP4 { get; set; }
        public string IMSRP8 { get; set; }
    }
}
