//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MannLabels
{
    using System;
    using System.Collections.Generic;
    
    public partial class F4104
    {
        public double IVAN8 { get; set; }
        public string IVXRT { get; set; }
        public double IVITM { get; set; }
        public decimal IVEXDJ { get; set; }
        public Nullable<decimal> IVEFTJ { get; set; }
        public string IVMCU { get; set; }
        public string IVCITM { get; set; }
        public string IVDSC1 { get; set; }
        public string IVDSC2 { get; set; }
        public string IVALN { get; set; }
        public string IVLITM { get; set; }
        public string IVCIRV { get; set; }
    }
}
