//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MannLabels
{
    using System;
    using System.Collections.Generic;
    
    public partial class F574101
    {
        public double QTITM { get; set; }
        public string QTLITM { get; set; }
        public Nullable<double> QTDIHI { get; set; }
        public Nullable<double> QTDIWI { get; set; }
        public Nullable<double> QTZ56DP { get; set; }
        public string QTZ56DCU { get; set; }
        public Nullable<double> QTZ56DIH { get; set; }
        public Nullable<double> QTZ56DIW { get; set; }
        public Nullable<double> QTZ56DID { get; set; }
        public string QTZ56DIU { get; set; }
        public Nullable<double> QTZ56CPL { get; set; }
        public Nullable<double> QTZ56LPP { get; set; }
        public Nullable<double> QTZ56MTMP { get; set; }
        public Nullable<double> QTZ56XTMP { get; set; }
        public string QTZ56TU { get; set; }
        public string QTZ56MD { get; set; }
        public string QTZ56LID { get; set; }
        public string QTZ56COO1 { get; set; }
        public string QTZ56COO2 { get; set; }
        public string QTZ56COO3 { get; set; }
        public string QTZ56COO4 { get; set; }
        public string QTZ56COO5 { get; set; }
        public string QTUSER { get; set; }
        public string QTPID { get; set; }
        public string QTJOBN { get; set; }
        public Nullable<decimal> QTUPMJ { get; set; }
        public Nullable<double> QTUPMT { get; set; }
        public Nullable<double> QTZ57IT { get; set; }
        public Nullable<double> QTZ57IC { get; set; }
        public Nullable<double> QTZ57IS { get; set; }
        public Nullable<double> QTZ57SS { get; set; }
        public Nullable<double> QTZ57PT { get; set; }
        public Nullable<double> QTZ57PKT { get; set; }
        public Nullable<double> QTZ57IMCU { get; set; }
        public Nullable<double> QTZ57IBR { get; set; }
        public Nullable<double> QTZ57GM { get; set; }
        public Nullable<double> QTZ57CC { get; set; }
        public Nullable<double> QTZ57OZ { get; set; }
        public Nullable<double> QTZ57TOZ { get; set; }
        public Nullable<double> QTZ57PS { get; set; }
        public string QTZ57UPC { get; set; }
        public Nullable<decimal> QTZ57DDJ { get; set; }
        public string QTZ57PL { get; set; }
        public Nullable<decimal> QTZ57LDJ { get; set; }
        public Nullable<double> QTZ57ICH { get; set; }
        public Nullable<double> QTZ57ICW { get; set; }
        public Nullable<double> QTZ57ICD { get; set; }
        public string QTZ57BIBS { get; set; }
        public string QTZ57BIBSD { get; set; }
        public string QTZ57BIBA { get; set; }
        public string QTZ57BIBAD { get; set; }
        public string QTZ57BIPL { get; set; }
        public string QTZ57BIPLD { get; set; }
        public string QTZ57BIP { get; set; }
        public string QTZ57BIPD { get; set; }
        public string QTZ57BIC { get; set; }
        public string QTZ57BICD { get; set; }
        public string QTZ57BIIP { get; set; }
        public string QTZ57BIIPD { get; set; }
        public string QTZ57BIOP { get; set; }
        public string QTZ57BIOPD { get; set; }
        public string QTZ57BIB { get; set; }
        public string QTZ57BIBD { get; set; }
        public Nullable<double> QTZ57BIIM { get; set; }
        public string QTZ57BIIU { get; set; }
        public Nullable<double> QTZ57BIOM { get; set; }
        public string QTZ57BIOU { get; set; }
        public string QTZ57BIFPL { get; set; }
        public string QTZ57BIFPLD { get; set; }
        public string QTZ57BIFSP { get; set; }
        public string QTZ57BIFSD { get; set; }
        public string QTZ57BIMPG { get; set; }
        public Nullable<double> QTZ57BINO { get; set; }
    }
}
