//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MannLabels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemsMaster
    {
        public int ItemNumer { get; set; }
        public string ItemFull { get; set; }
        public string ItemDesc { get; set; }
        public string BrandAbbrv { get; set; }
        public string BrandFull { get; set; }
        public string GTIN { get; set; }
        public string WalmartCode { get; set; }
    }
}
