//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MannLabels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabelField
    {
        public int idx { get; set; }
        public int LabelID { get; set; }
        public string FieldName { get; set; }
        public int FieldOrdinal { get; set; }
        public string FieldType { get; set; }
    
        public virtual LabelJob LabelJob { get; set; }
    }
}
