//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MannLabels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LabelPrintModels : DbContext
    {
        public LabelPrintModels()
            : base("name=LabelPrintModels")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COO_List> COO_List { get; set; }
        public virtual DbSet<ItemsMaster> ItemsMasters { get; set; }
        public virtual DbSet<UserList> UserLists { get; set; }
        public virtual DbSet<Printer> Printers { get; set; }
        public virtual DbSet<SrcAddress> SrcAddresses { get; set; }
        public virtual DbSet<AltLabelItem> AltLabelItems { get; set; }
    }
}
