//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MannLabels
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserList
    {
        public int idx { get; set; }
        public string Logon { get; set; }
        public string Password { get; set; }
        public int Printer { get; set; }
        public string Email { get; set; }
    
        public virtual Printer Printer1 { get; set; }
    }
}
